{
 "title": "BTC Purchases",
 "tags": [
  "btc",
  "purchases"
 ],
 "time": { "from": "2024-11-30T23:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cumulative vs Current Invested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT\r\n  date,\r\n  SUM(purchase_value) OVER (\r\n    ORDER BY\r\n      date\r\n  ) AS \"Cumulative Invested\"\r\nFROM\r\n  sayso_purchases\r\nORDER BY\r\n  date;"
    },
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT date, SUM(current_value) OVER (ORDER BY date) AS \"Cumulative Current\" FROM sayso_purchases ORDER BY date;"
    }
   ]
  },
  {
   "title": "BTC-EUR - Earliest v Latest",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT\r\n  btc_value AS \"First Recorded VAL\"\r\nFROM\r\n  sayso_btc_eur_price_hist\r\nORDER BY\r\n  date ASC\r\nLIMIT\r\n  1;"
    },
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT btc_value AS \"Latest Recorded VAL\"\r\nFROM sayso_btc_eur_price_hist\r\nORDER BY date DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Invested Purchases at Purchase Time vs Current",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT\r\n  date,\r\n  purchase_value as \"Invested Price\",\r\n  current_value as \"Current Price\"\r\nFROM\r\n  sayso_purchases\r\nORDER BY\r\n  date;"
    }
   ]
  },
  {
   "title": "BTC-EUR Performance + Moving Averages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT\r\n  date,\r\n  btc_value as \"BTC-EUR\",\r\n  AVG(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 9 PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS \"Moving Avg 10 - ma_10\",\r\n  AVG(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 49 PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS \"Moving Avg 50 - ma_50\",\r\n  AVG(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 19 PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS \"Moving Avg 20 - ma_20\"\r\nFROM\r\n  sayso_btc_eur_price_hist;"
    }
   ]
  },
  {
   "title": "BTC Purchases Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawCode": "SELECT\n  date AS \"time\",\n  SUM(purchase_value) OVER (ORDER BY date) AS \"cumulative_invested\",\n  SUM(current_value) OVER (ORDER BY date) AS \"cumulative_current\"\nFROM sayso_purchases\nORDER BY date;",
     "rawSql": "SELECT\r\n  date AS \"time\",\r\n  SUM(purchase_value) OVER (\r\n    ORDER BY\r\n      date\r\n  ) AS \"Cumulative Invested\",\r\n  SUM(current_value) OVER (\r\n    ORDER BY\r\n      date\r\n  ) AS \"Cumulative Current\"\r\nFROM\r\n  sayso_purchases\r\nORDER BY\r\n  date;"
    }
   ]
  },
  {
   "title": "BTC-EUR Price + Volatility Bands",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sayso_db",
     "rawSql": "SELECT\r\n  date AS time,\r\n  btc_value,\r\n  STDDEV(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 19 PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS stddev,\r\n  -- Upper band\r\n  AVG(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 19 PRECEDING\r\n      AND CURRENT ROW\r\n  ) + 2 * STDDEV(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 19 PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS upper_band,\r\n  -- Lower band\r\n  AVG(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 19 PRECEDING\r\n      AND CURRENT ROW\r\n  ) - 2 * STDDEV(btc_value) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN 19 PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS lower_band\r\nFROM\r\n  sayso_btc_eur_price_hist;"
    }
   ]
  }
 ]
}